# This was just for testing that the app runs on MS SQL/SQL Server by running it on Docker

# services:
#   sql:
#     image: mcr.microsoft.com/azure-sql-edge
#     container_name: sql
#     environment: 
#       ACCEPT_EULA: "1"
#       MSSQL_SA_PASSWORD: "Password@1"
#     ports:
#       - "1433:1433"
      